import { Card, MbscCardOptions } from '../classes/cards';
export { Card, MbscCardOptions };
import { Calendar, MbscCalendarOptions } from '../presets/calendar';
export { Calendar, MbscCalendarOptions };
import { Color, MbscColorOptions } from '../classes/color';
export { Color, MbscColorOptions };
import { MbscDatetimeOptions } from '../presets/datetimebase';
import { DateTime } from '../presets/datetime';
export { DateTime, MbscDatetimeOptions };
import { Eventcalendar, MbscEventcalendarOptions } from '../presets/eventcalendar';
export { Eventcalendar, MbscEventcalendarOptions };
import { Form, MbscFormOptions } from '../classes/forms';
export { Form, MbscFormOptions };
import { Page, MbscPageOptions } from '../classes/page';
export { Page, MbscPageOptions };
import { ImageScroller, MbscImageOptions } from '../presets/image';
export { ImageScroller, MbscImageOptions };
import { ListView, MbscListviewOptions } from '../classes/listview';
export { ListView, MbscListviewOptions };
import { Optionlist, MbscOptionlistOptions } from '../classes/optionlist';
export { Optionlist, MbscOptionlistOptions };
import { Measurement, MbscMeasurementOptions } from '../presets/measurement';
import { Mass, MbscMassOptions } from '../presets/mass';
import { Distance, MbscDistanceOptions } from '../presets/distance';
import { Force, MbscForceOptions } from '../presets/force';
import { Speed, MbscSpeedOptions } from '../presets/speed';
import { Temperature, MbscTemperatureOptions } from '../presets/temperature';
export { Measurement, Mass, Distance, Force, Speed, Temperature, MbscMeasurementOptions, MbscMassOptions, MbscForceOptions, MbscSpeedOptions, MbscTemperatureOptions, MbscDistanceOptions };
import { Navigation, MbscNavOptions } from '../classes/navigation';
export { Navigation, MbscNavOptions };
import { NumberScroller, MbscNumberOptions } from '../presets/number';
export { NumberScroller, MbscNumberOptions };
import { Numpad, MbscNumpadOptions } from '../classes/numpad';
export { Numpad, MbscNumpadOptions };
import { RangePicker, MbscRangeOptions } from '../presets/range';
export { RangePicker, MbscRangeOptions };
import { Scroller, MbscScrollerOptions } from '../classes/scroller';
export { Scroller, MbscScrollerOptions };
import { ScrollView, MbscScrollViewOptions } from '../classes/scrollview';
export { ScrollView, MbscScrollViewOptions };
import { Select, MbscSelectOptions } from '../presets/select';
export { Select, MbscSelectOptions };
import { Timer, MbscTimerOptions } from '../presets/timer';
export { Timer, MbscTimerOptions };
import { Timespan, MbscTimespanOptions } from '../presets/timespan';
export { Timespan, MbscTimespanOptions };
import { Treelist, MbscTreelistOptions } from '../presets/treelist';
export { Treelist, MbscTreelistOptions };
import { Widget, MbscWidgetOptions } from '../classes/widget';
export { Widget, MbscWidgetOptions };

import { IMobiscroll as _IMobiscroll } from '../core/core';

export interface IMobiscroll extends _IMobiscroll {
    card(selector: string, options?: MbscCardOptions): Card;
    calendar(selector: string, options?: MbscCalendarOptions): Calendar;
    color(selector: string, options?: MbscColorOptions): Color;
    datetime(selector: string, options?: MbscDatetimeOptions): DateTime;
    date(selector: string, options?: MbscDatetimeOptions): DateTime;
    time(selector: string, options?: MbscDatetimeOptions): DateTime;
    eventcalendar(selector: string, options?: MbscEventcalendarOptions): Eventcalendar;
    form(selector: string, options?: MbscFormOptions): Form;
    page(selector: string, options?: MbscPageOptions): Page;
    image(selector: string, options?: MbscImageOptions): ImageScroller;
    listview(selector: string, options?: MbscListviewOptions): ListView;
    optionlist(selector: string, options?: MbscOptionlistOptions): Optionlist;
    measurement(selector: string, options?: MbscMeasurementOptions): Measurement;
    mass(selector: string, options?: MbscMassOptions): Mass;
    distance(selector: string, options?: MbscDistanceOptions): Distance;
    force(selector: string, options?: MbscForceOptions): Force;
    speed(selector: string, options?: MbscSpeedOptions): Speed;
    temperature(selector: string, options?: MbscTemperatureOptions): Temperature;
    nav(selector: string, options?: MbscNavOptions): Navigation;
    number(selector: string, options?: MbscNumberOptions): NumberScroller;
    numpad(selector: string, options?: MbscNumpadOptions): Numpad;
    range(selector: string, options?: MbscRangeOptions): RangePicker;
    scroller(selector: string, options?: MbscScrollerOptions): Scroller;
    scrollview(selector: string, options?: MbscScrollViewOptions): ScrollView;
    select(selector: string, options?: MbscSelectOptions): Select;
    timer(selector: string, options?: MbscTimerOptions): Timer;
    timespan(selector: string, options?: MbscTimespanOptions): Timespan;
    treelist(selector: string, options?: MbscTreelistOptions): Treelist;
    widget(selector: string, options?: MbscWidgetOptions): Widget;
}

export const mobiscroll: IMobiscroll;
export as namespace mobiscroll;
export default mobiscroll;
